"""Antonym pairs for contradiction detection in diff classification.

Pairs sourced from WordNet (one-time extraction via scripts/extract_antonyms.py)
and manually curated programming/technical antonyms. Each pair is (term_a, term_b)
where presence of term_a in one text and term_b in another signals contradiction.

Minimum term length is 4 characters to avoid false substring matches.
"""

ANTONYM_PAIRS = (
    # --- Programming / technical domain ---
    ('synchronous', 'asynchronous'),
    ('single-threaded', 'multi-threaded'),
    ('single threaded', 'multi threaded'),
    ('mutable', 'immutable'),
    ('stateful', 'stateless'),
    ('monolith', 'microservice'),
    ('blocking', 'non-blocking'),
    ('centralized', 'decentralized'),
    ('coupled', 'decoupled'),
    ('encrypted', 'unencrypted'),
    ('authenticated', 'unauthenticated'),
    ('horizontal', 'vertical'),
    ('manual', 'automated'),
    ('relational', 'non-relational'),
    ('normalized', 'denormalized'),
    ('server-side', 'client-side'),
    ('upstream', 'downstream'),
    ('pull-based', 'push-based'),
    ('eager', 'lazy'),
    ('strongly typed', 'weakly typed'),
    ('dynamically typed', 'statically typed'),
    ('compiled', 'interpreted'),
    ('optimistic', 'pessimistic'),
    ('read-heavy', 'write-heavy'),
    ('idempotent', 'non-idempotent'),
    ('tolerant', 'intolerant'),
    ('schema-on-read', 'schema-on-write'),
    ('in-memory', 'on-disk'),
    ('containerized', 'bare-metal'),
    ('open-source', 'proprietary'),
    ('embedded', 'standalone'),
    ('type-safe', 'type-unsafe'),
    ('thread-safe', 'thread-unsafe'),
    ('production', 'development'),
    ('deprecated', 'recommended'),
    ('required', 'optional'),

    # --- General adjectives (from WordNet, curated for prose relevance) ---
    ('abstract', 'concrete'),
    ('active', 'inactive'),
    ('active', 'passive'),
    ('adequate', 'inadequate'),
    ('affirmative', 'negative'),
    ('ascending', 'descending'),
    ('compatible', 'incompatible'),
    ('complete', 'incomplete'),
    ('conditional', 'unconditional'),
    ('consistent', 'inconsistent'),
    ('constructive', 'destructive'),
    ('continuous', 'discontinuous'),
    ('correct', 'incorrect'),
    ('dependent', 'independent'),
    ('direct', 'indirect'),
    ('dynamic', 'static'),
    ('efficient', 'inefficient'),
    ('essential', 'inessential'),
    ('exclusive', 'inclusive'),
    ('explicit', 'implicit'),
    ('external', 'internal'),
    ('flexible', 'inflexible'),
    ('formal', 'informal'),
    ('heterogeneous', 'homogeneous'),
    ('logical', 'illogical'),
    ('necessary', 'unnecessary'),
    ('negative', 'positive'),
    ('obligatory', 'optional'),
    ('permanent', 'temporary'),
    ('persistent', 'transient'),
    ('portable', 'unportable'),
    ('private', 'public'),
    ('productive', 'unproductive'),
    ('progressive', 'regressive'),
    ('reliable', 'unreliable'),
    ('reproducible', 'unreproducible'),
    ('reversible', 'irreversible'),
    ('robust', 'fragile'),
    ('safe', 'unsafe'),
    ('secure', 'insecure'),
    ('significant', 'insignificant'),
    ('stable', 'unstable'),
    ('sufficient', 'insufficient'),
    ('transparent', 'opaque'),
    ('valid', 'invalid'),
    ('visible', 'invisible'),
    ('voluntary', 'involuntary'),
    ('linear', 'nonlinear'),
    ('deterministic', 'nondeterministic'),
    ('modular', 'monolithic'),
    ('ordered', 'unordered'),
    ('parallel', 'serial'),
    ('sequential', 'concurrent'),
    ('typical', 'atypical'),
    ('vulnerable', 'invulnerable'),
    )
